version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      # Removed MYSQL_USER and MYSQL_PASSWORD as per instructions
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      # Updated PMA_USER and PMA_PASSWORD to reflect the removal of MYSQL_USER
      PMA_USER: root
      PMA_PASSWORD: root_password
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge